### ISSUE TITLE
call renderNoteLabel even if it doesn't have a keyboardShortcut.

### ISSUE THREAD

**Issue by ritz078** [iqnivek/react-piano#22]
https://github.com/iqnivek/react-piano/blob/895a6c9455aca56d47c0fac2c5497a36d2fb6bab/src/Piano.js#L186

I want to show midiNumbers. But currently i can't show it for keys that don't have keyboardShortcut due to this check.

**Comment by iqnivek** [comment]
Yeah this change makes total sense, I'd been considering changing this behavior too! PR looks good but going to double check it later today.
