### ISSUE TITLE
Make this a controlled component

### ISSUE THREAD

**Issue by ritz078** [iqnivek/react-piano#26]
Currently, the component behaves both as controlled and uncontrolled.

**Comment by iqnivek** [comment]
You mean with the combination of internal state (activeNotes) and `props.playbackNotes`, right? If so, yeah I see what you're saying. I'd have to experiment with it to see how well a controlled version works.  

I assume a controlled version of the component would get rid of `props.playbackNotes`, replace `state.activeNotes` with `props.activeNotes`, and you'd have to update `props.activeNotes` yourself inside `onPlayNote/onStopNote`? I think my original concern was that this approach does add a bit of additional complexity for the end user, whereas the hybrid controlled/uncontrolled approach is simpler to use at the cost of having a less elegant API. I'll think about it though.

**Comment by ritz078** [comment]
I understand that but the problem is that currently the component works both as controlled and uncontrolled component so I have to actually change the logic when the mode changes. In any case if you are trying to make a real app you will need to write some code for playing the music which means it's just few simple steps to save in the state. React docs also says that the component should just be one of them. Currently it becomes confusing if it changes from controlled to uncontrolled.

Other solution that's possible is you can export a separate `ControlledPiano` component that's a wrapper over `UncontrolledPiano`.

**Comment by iqnivek** [comment]
Yeah, I see the problem and I think I agree. Piano actually used to be a controlled component in pre-v1, but I'd changed the API without realizing the downsides of that change. I'll try to change this soon and release a v3. Thanks for the input.

**Comment by iqnivek** [comment]
This is now shipped in v3.0.0 published today! `Piano` is now a "controllable" component where you can let it manage state itself, OR pass in activeNotes which override its local state. `Piano` is a lightweight wrapper around `ControlledPiano` which is a fully controlled component that gives you more fine-grained control. See #36 for more details.

This change definitely makes the inner logic nicer, so thanks for the suggestion @ritz078. Hope this addresses your concern.
